<a href="https://colab.research.google.com/github/PTIch06/YasynskyiColab/blob/main/Lab2_Yasynskyi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Лабораторна робота №2
##з дисципліни "Нейронні мережі"
###студента групи КН-31/2
###Ясинського Дениса
###Варіант №11

- створити набір даних із заданим розподілом (розподіл та розмір за власним рішенням), визначити його властивості (shape, rank, size, axis)

In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [9]:
data = np.random.uniform(0,10, size=(13, 13)).astype(int)
tensor = tf.convert_to_tensor(data)
print(tensor)

<tf.Tensor: shape=(13, 13), dtype=int64, numpy=
array([[7, 7, 3, 7, 9, 8, 8, 5, 1, 2, 6, 0, 6],
       [1, 9, 0, 6, 6, 1, 7, 7, 9, 6, 1, 1, 9],
       [7, 6, 8, 3, 9, 3, 6, 4, 8, 9, 4, 1, 8],
       [5, 7, 7, 4, 0, 1, 3, 1, 4, 5, 5, 0, 2],
       [4, 7, 6, 8, 5, 4, 6, 7, 1, 6, 0, 1, 0],
       [6, 0, 2, 2, 0, 8, 3, 3, 1, 6, 8, 8, 8],
       [7, 9, 7, 2, 5, 6, 2, 4, 8, 4, 8, 0, 5],
       [1, 6, 6, 8, 6, 5, 2, 8, 4, 5, 5, 5, 1],
       [3, 8, 1, 5, 9, 8, 0, 2, 6, 2, 9, 9, 1],
       [7, 4, 6, 2, 2, 3, 6, 6, 9, 1, 1, 8, 0],
       [1, 4, 7, 3, 6, 0, 4, 6, 1, 5, 6, 2, 9],
       [8, 0, 9, 2, 4, 3, 4, 5, 9, 1, 9, 6, 2],
       [5, 5, 7, 6, 9, 9, 1, 9, 6, 4, 5, 3, 7]])>

- продемонструвати основні математичні операції над тензорами

In [11]:
tensor = tf.constant([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [13]:
print(tensor)
print(tensor + 1)
print(tensor * -1)









tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -9]], shape=(3, 3), dtype=int32)


In [22]:
print(tf.abs(tf.multiply(tensor, -1)))
print(tf.reduce_max(tensor).numpy())
print(tf.reduce_min(tensor).numpy())

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
9
1


- провести CRUD операції над даними, reshape, інтеграцію з np.array, pd.DataFrame)

In [33]:
tensor = tf.constant([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]])

In [36]:
print(tensor)
print(tf.reshape(tensor, shape=(1, 12)))

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)
tf.Tensor([[ 1  2  3  4  5  6  7  8  9 10 11 12]], shape=(1, 12), dtype=int32)


In [38]:
df = np.array(tensor)
df

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)

In [35]:
df = pd.DataFrame(tensor)
df

0                                     1  \
0   tf.Tensor(1, shape=(), dtype=int32)   tf.Tensor(2, shape=(), dtype=int32)   
1   tf.Tensor(4, shape=(), dtype=int32)   tf.Tensor(5, shape=(), dtype=int32)   
2   tf.Tensor(7, shape=(), dtype=int32)   tf.Tensor(8, shape=(), dtype=int32)   
3  tf.Tensor(10, shape=(), dtype=int32)  tf.Tensor(11, shape=(), dtype=int32)   

                                      2  
0   tf.Tensor(3, shape=(), dtype=int32)  
1   tf.Tensor(6, shape=(), dtype=int32)  
2   tf.Tensor(9, shape=(), dtype=int32)  
3  tf.Tensor(12, shape=(), dtype=int32)